name: login_sqlite_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  # ğŸ”‘ 
  intl: ^0.18.0 
  # Firebase
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.0
  # Notificaciones locales
  flutter_local_notifications: ^17.2.2
  # SQLite
  sqflite: ^2.3.0
  path: ^1.8.3
  # GestiÃ³n de sesiÃ³n
  shared_preferences: ^2.2.1
  # Ãconos de estilo iOS
  cupertino_icons: ^1.0.8
  # Calendario
  table_calendar: ^3.0.9
  # Para encriptar la contraseÃ±a de forma segura (Opcional)
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
